// <auto-generated />
using System;
using FantasyWarrior.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FantasyWarrior.Data.Migrations
{
    [DbContext(typeof(FantasyWarriorDbContext))]
    [Migration("20260807154646_ForwardDatedRosterSpots")]
    partial class ForwardDatedRosterSpots
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FantasyWarrior.Data.Entities.CockcoinAward", b =>
                {
                    b.Property<long>("CockcoinAwardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CockcoinAwardId"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("AwardedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CockcoinAwardId");

                    b.HasIndex("UserId");

                    b.ToTable("CockcoinAwards", (string)null);
                });

            modelBuilder.Entity("FantasyWarrior.Data.Entities.DraftPick", b =>
                {
                    b.Property<int>("DraftPickId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DraftPickId"));

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentTeamId")
                        .HasColumnType("int");

                    b.Property<int>("LeagueId")
                        .HasColumnType("int");

                    b.Property<int>("OriginalTeamId")
                        .HasColumnType("int");

                    b.Property<int?>("PickInRound")
                        .HasColumnType("int");

                    b.Property<long?>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<int>("Round")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UsedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("DraftPickId");

                    b.HasIndex("OriginalTeamId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("CurrentTeamId", "Year", "Round");

                    b.HasIndex("LeagueId", "Year", "Round", "OriginalTeamId")
                        .IsUnique();

                    b.ToTable("DraftPicks", (string)null);
                });

            modelBuilder.Entity("FantasyWarrior.Data.Entities.Game", b =>
                {
                    b.Property<long>("GameId")
                        .HasColumnType("bigint");

                    b.Property<int>("AwayScore")
                        .HasColumnType("int");

                    b.Property<string>("AwayTeamAbbrev")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .IsFixedLength();

                    b.Property<DateOnly>("GameDate")
                        .HasColumnType("date");

                    b.Property<byte>("GameType")
                        .HasColumnType("tinyint");

                    b.Property<int>("HomeScore")
                        .HasColumnType("int");

                    b.Property<string>("HomeTeamAbbrev")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .IsFixedLength();

                    b.Property<string>("LastPeriodType")
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("char(8)")
                        .IsFixedLength();

                    b.Property<DateTime>("SyncedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("GameId");

                    b.HasIndex("AwayTeamAbbrev");

                    b.HasIndex("GameDate");

                    b.HasIndex("HomeTeamAbbrev");

                    b.HasIndex("Season", "GameType", "GameDate");

                    b.ToTable("Games", (string)null);
                });

            modelBuilder.Entity("FantasyWarrior.Data.Entities.League", b =>
                {
                    b.Property<int>("LeagueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeagueId"));

                    b.Property<int>("ActiveDefense")
                        .HasColumnType("int");

                    b.Property<int>("ActiveForwards")
                        .HasColumnType("int");

                    b.Property<int>("ActiveGoalies")
                        .HasColumnType("int");

                    b.Property<long?>("CapAmount")
                        .HasColumnType("bigint");

                    b.Property<int>("CommissionerUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("DefaultCapHit")
                        .HasColumnType("bigint");

                    b.Property<int?>("DraftRounds")
                        .HasColumnType("int");

                    b.Property<string>("JoinCode")
                        .IsRequired()
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int?>("RosterMax")
                        .HasColumnType("int");

                    b.Property<int?>("RosterMin")
                        .HasColumnType("int");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("char(8)")
                        .IsFixedLength();

                    b.HasKey("LeagueId");

                    b.HasIndex("CommissionerUserId");

                    b.HasIndex("JoinCode")
                        .IsUnique();

                    b.ToTable("Leagues", (string)null);
                });

            modelBuilder.Entity("FantasyWarrior.Data.Entities.LeagueMember", b =>
                {
                    b.Property<int>("LeagueId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("JoinedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("LeagueId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("LeagueMembers", (string)null);
                });

            modelBuilder.Entity("FantasyWarrior.Data.Entities.LeagueScoringRule", b =>
                {
                    b.Property<int>("LeagueId")
                        .HasColumnType("int");

                    b.Property<string>("StatKey")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<double>("PointValue")
                        .HasColumnType("float");

                    b.HasKey("LeagueId", "StatKey");

                    b.ToTable("LeagueScoringRules", (string)null);
                });

            modelBuilder.Entity("FantasyWarrior.Data.Entities.Message", b =>
                {
                    b.Property<long>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MessageId"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("LeagueId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReadUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("RecipientUserId")
                        .HasColumnType("int");

                    b.Property<int>("SenderUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("MessageId");

                    b.HasIndex("SenderUserId");

                    b.HasIndex("RecipientUserId", "LeagueId")
                        .HasDatabaseName("IX_Messages_Unread")
                        .HasFilter("[ReadUtc] IS NULL");

                    b.HasIndex("LeagueId", "SenderUserId", "RecipientUserId", "SentUtc");

                    b.ToTable("Messages", (string)null);
                });

            modelBuilder.Entity("FantasyWarrior.Data.Entities.NewsItem", b =>
                {
                    b.Property<int>("NewsItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NewsItemId"));

                    b.Property<string>("Body")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ExternalKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("FetchedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Headline")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long?>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<string>("PlayerName")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("PublishedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Url")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("NewsItemId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("PublishedUtc")
                        .IsDescending();

                    b.HasIndex("Source", "ExternalKey")
                        .IsUnique();

                    b.ToTable("NewsItems", (string)null);
                });

            modelBuilder.Entity("FantasyWarrior.Data.Entities.NhlTeam", b =>
                {
                    b.Property<string>("Abbrev")
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .IsFixedLength();

                    b.Property<string>("ConferenceName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DivisionName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Abbrev");

                    b.ToTable("NhlTeams", (string)null);

                    b.HasData(
                        new
                        {
                            Abbrev = "BOS",
                            ConferenceName = "Eastern",
                            DivisionName = "Atlantic",
                            LogoUrl = "https://assets.nhle.com/logos/nhl/svg/BOS_light.svg",
                            Name = "Boston Bruins"
                        },
                        new
                        {
                            Abbrev = "BUF",
                            ConferenceName = "Eastern",
                            DivisionName = "Atlantic",
                            LogoUrl = "https://assets.nhle.com/logos/nhl/svg/BUF_light.svg",
                            Name = "Buffalo Sabres"
                        },
                        new
                        {
                            Abbrev = "DET",
                            ConferenceName = "Eastern",
                            DivisionName = "Atlantic",
                            LogoUrl = "https://assets.nhle.com/logos/nhl/svg/DET_light.svg",
                            Name = "Detroit Red Wings"
                        },
                        new
                        {
                            Abbrev = "FLA",
                            ConferenceName = "Eastern",
                            DivisionName = "Atlantic",
                            LogoUrl = "https://assets.nhle.com/logos/nhl/svg/FLA_light.svg",
                            Name = "Florida Panthers"
                        },
                        new
                        {
                            Abbrev = "MTL",
                            ConferenceName = "Eastern",
                            DivisionName = "Atlantic",
                            LogoUrl = "https://assets.nhle.com/logos/nhl/svg/MTL_light.svg",
                            Name = "Montreal Canadiens"
                        },
                        new
                        {
                            Abbrev = "OTT",
                            ConferenceName = "Eastern",
                            DivisionName = "Atlantic",
                            LogoUrl = "https://assets.nhle.com/logos/nhl/svg/OTT_light.svg",
                            Name = "Ottawa Senators"
                        },
                        new
                        {
                            Abbrev = "TBL",
                            ConferenceName = "Eastern",
                            DivisionName = "Atlantic",
                            LogoUrl = "https://assets.nhle.com/logos/nhl/svg/TBL_light.svg",
                            Name = "Tampa Bay Lightning"
                        },
                        new
                        {
                            Abbrev = "TOR",
                            ConferenceName = "Eastern",
                            DivisionName = "Atlantic",
                            LogoUrl = "https://assets.nhle.com/logos/nhl/svg/TOR_light.svg",
                            Name = "Toronto Maple Leafs"
                        },
                        new
                        {
                            Abbrev = "CAR",
                            ConferenceName = "Eastern",
                            DivisionName = "Metropolitan",
                            LogoUrl = "https://assets.nhle.com/logos/nhl/svg/CAR_light.svg",
                            Name = "Carolina Hurricanes"
                        },
                        new
                        {
                            Abbrev = "CBJ",
                            ConferenceName = "Eastern",
                            DivisionName = "Metropolitan",
                            LogoUrl = "https://assets.nhle.com/logos/nhl/svg/CBJ_light.svg",
                            Name = "Columbus Blue Jackets"
                        },
                        new
                        {
                            Abbrev = "NJD",
                            ConferenceName = "Eastern",
                            DivisionName = "Metropolitan",
                            LogoUrl = "https://assets.nhle.com/logos/nhl/svg/NJD_light.svg",
                            Name = "New Jersey Devils"
                        },
                        new
                        {
                            Abbrev = "NYI",
                            ConferenceName = "Eastern",
                            DivisionName = "Metropolitan",
                            LogoUrl = "https://assets.nhle.com/logos/nhl/svg/NYI_light.svg",
                            Name = "New York Islanders"
                        },
                        new
                        {
                            Abbrev = "NYR",
                            ConferenceName = "Eastern",
                            DivisionName = "Metropolitan",
                            LogoUrl = "https://assets.nhle.com/logos/nhl/svg/NYR_light.svg",
                            Name = "New York Rangers"
                        },
                        new
                        {
                            Abbrev = "PHI",
                            ConferenceName = "Eastern",
                            DivisionName = "Metropolitan",
                            LogoUrl = "https://assets.nhle.com/logos/nhl/svg/PHI_light.svg",
                            Name = "Philadelphia Flyers"
                        },
                        new
                        {
                            Abbrev = "PIT",
                            ConferenceName = "Eastern",
                            DivisionName = "Metropolitan",
                            LogoUrl = "https://assets.nhle.com/logos/nhl/svg/PIT_light.svg",
                            Name = "Pittsburgh Penguins"
                        },
                        new
                        {
                            Abbrev = "WSH",
                            ConferenceName = "Eastern",
                            DivisionName = "Metropolitan",
                            LogoUrl = "https://assets.nhle.com/logos/nhl/svg/WSH_light.svg",
                            Name = "Washington Capitals"
                        },
                        new
                        {
                            Abbrev = "CHI",
                            ConferenceName = "Western",
                            DivisionName = "Central",
                            LogoUrl = "https://assets.nhle.com/logos/nhl/svg/CHI_light.svg",
                            Name = "Chicago Blackhawks"
                        },
                        new
                        {
                            Abbrev = "COL",
                            ConferenceName = "Western",
                            DivisionName = "Central",
                            LogoUrl = "https://assets.nhle.com/logos/nhl/svg/COL_light.svg",
                            Name = "Colorado Avalanche"
                        },
                        new
                        {
                            Abbrev = "DAL",
                            ConferenceName = "Western",
                            DivisionName = "Central",
                            LogoUrl = "https://assets.nhle.com/logos/nhl/svg/DAL_light.svg",
                            Name = "Dallas Stars"
                        },
                        new
                        {
                            Abbrev = "MIN",
                            ConferenceName = "Western",
                            DivisionName = "Central",
                            LogoUrl = "https://assets.nhle.com/logos/nhl/svg/MIN_light.svg",
                            Name = "Minnesota Wild"
                        },
                        new
                        {
                            Abbrev = "NSH",
                            ConferenceName = "Western",
                            DivisionName = "Central",
                            LogoUrl = "https://assets.nhle.com/logos/nhl/svg/NSH_light.svg",
                            Name = "Nashville Predators"
                        },
                        new
                        {
                            Abbrev = "STL",
                            ConferenceName = "Western",
                            DivisionName = "Central",
                            LogoUrl = "https://assets.nhle.com/logos/nhl/svg/STL_light.svg",
                            Name = "St. Louis Blues"
                        },
                        new
                        {
                            Abbrev = "UTA",
                            ConferenceName = "Western",
                            DivisionName = "Central",
                            LogoUrl = "https://assets.nhle.com/logos/nhl/svg/UTA_light.svg",
                            Name = "Utah Mammoth"
                        },
                        new
                        {
                            Abbrev = "WPG",
                            ConferenceName = "Western",
                            DivisionName = "Central",
                            LogoUrl = "https://assets.nhle.com/logos/nhl/svg/WPG_light.svg",
                            Name = "Winnipeg Jets"
                        },
                        new
                        {
                            Abbrev = "ANA",
                            ConferenceName = "Western",
                            DivisionName = "Pacific",
                            LogoUrl = "https://assets.nhle.com/logos/nhl/svg/ANA_light.svg",
                            Name = "Anaheim Ducks"
                        },
                        new
                        {
                            Abbrev = "CGY",
                            ConferenceName = "Western",
                            DivisionName = "Pacific",
                            LogoUrl = "https://assets.nhle.com/logos/nhl/svg/CGY_light.svg",
                            Name = "Calgary Flames"
                        },
                        new
                        {
                            Abbrev = "EDM",
                            ConferenceName = "Western",
                            DivisionName = "Pacific",
                            LogoUrl = "https://assets.nhle.com/logos/nhl/svg/EDM_light.svg",
                            Name = "Edmonton Oilers"
                        },
                        new
                        {
                            Abbrev = "LAK",
                            ConferenceName = "Western",
                            DivisionName = "Pacific",
                            LogoUrl = "https://assets.nhle.com/logos/nhl/svg/LAK_light.svg",
                            Name = "Los Angeles Kings"
                        },
                        new
                        {
                            Abbrev = "SEA",
                            ConferenceName = "Western",
                            DivisionName = "Pacific",
                            LogoUrl = "https://assets.nhle.com/logos/nhl/svg/SEA_light.svg",
                            Name = "Seattle Kraken"
                        },
                        new
                        {
                            Abbrev = "SJS",
                            ConferenceName = "Western",
                            DivisionName = "Pacific",
                            LogoUrl = "https://assets.nhle.com/logos/nhl/svg/SJS_light.svg",
                            Name = "San Jose Sharks"
                        },
                        new
                        {
                            Abbrev = "VAN",
                            ConferenceName = "Western",
                            DivisionName = "Pacific",
                            LogoUrl = "https://assets.nhle.com/logos/nhl/svg/VAN_light.svg",
                            Name = "Vancouver Canucks"
                        },
                        new
                        {
                            Abbrev = "VGK",
                            ConferenceName = "Western",
                            DivisionName = "Pacific",
                            LogoUrl = "https://assets.nhle.com/logos/nhl/svg/VGK_light.svg",
                            Name = "Vegas Golden Knights"
                        });
                });

            modelBuilder.Entity("FantasyWarrior.Data.Entities.Period", b =>
                {
                    b.Property<int>("PeriodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PeriodId"));

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("FinalizedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("GameCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("LockUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("char(8)")
                        .IsFixedLength();

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("PeriodId");

                    b.HasIndex("Season", "Number")
                        .IsUnique();

                    b.HasIndex("Season", "StartDate");

                    b.ToTable("Periods", (string)null);
                });

            modelBuilder.Entity("FantasyWarrior.Data.Entities.Player", b =>
                {
                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<string>("BirthCountry")
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("CapWagesSlug")
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.Property<DateTime?>("CareerStatsSyncedUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DraftChecked")
                        .HasColumnType("bit");

                    b.Property<int?>("DraftOverall")
                        .HasColumnType("int");

                    b.Property<int?>("DraftRound")
                        .HasColumnType("int");

                    b.Property<string>("DraftTeamAbbrev")
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .IsFixedLength();

                    b.Property<int?>("DraftYear")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("HeadshotUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("HeightCm")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime>("LastSyncedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.Property<string>("PositionGroup")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasComputedColumnSql("CASE WHEN [Position] = 'D' THEN 'D' WHEN [Position] = 'G' THEN 'G' ELSE 'F' END", true)
                        .IsFixedLength();

                    b.Property<string>("ShootsCatches")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)");

                    b.Property<int?>("SweaterNumber")
                        .HasColumnType("int");

                    b.Property<string>("TeamAbbrev")
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .IsFixedLength();

                    b.Property<int?>("WeightKg")
                        .HasColumnType("int");

                    b.HasKey("PlayerId");

                    b.HasIndex("CareerStatsSyncedUtc");

                    b.HasIndex("DraftChecked")
                        .HasFilter("[DraftChecked] = 0");

                    b.HasIndex("Status");

                    b.HasIndex("TeamAbbrev");

                    b.HasIndex("LastName", "FirstName");

                    b.ToTable("Players", (string)null);
                });

            modelBuilder.Entity("FantasyWarrior.Data.Entities.PlayerCareerSeasonStat", b =>
                {
                    b.Property<long>("PlayerCareerSeasonStatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PlayerCareerSeasonStatId"));

                    b.Property<int?>("Assists")
                        .HasColumnType("int");

                    b.Property<byte>("GameType")
                        .HasColumnType("tinyint");

                    b.Property<int>("GamesPlayed")
                        .HasColumnType("int");

                    b.Property<int?>("Goals")
                        .HasColumnType("int");

                    b.Property<int?>("GoalsAgainst")
                        .HasColumnType("int");

                    b.Property<double?>("GoalsAgainstAvg")
                        .HasColumnType("float");

                    b.Property<string>("LeagueAbbrev")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("Losses")
                        .HasColumnType("int");

                    b.Property<int?>("OtLosses")
                        .HasColumnType("int");

                    b.Property<int?>("Pim")
                        .HasColumnType("int");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<int?>("PlusMinus")
                        .HasColumnType("int");

                    b.Property<int?>("Points")
                        .HasColumnType("int");

                    b.Property<double?>("SavePctg")
                        .HasColumnType("float");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("char(8)")
                        .IsFixedLength();

                    b.Property<int?>("Shutouts")
                        .HasColumnType("int");

                    b.Property<string>("TeamName")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int?>("Wins")
                        .HasColumnType("int");

                    b.HasKey("PlayerCareerSeasonStatId");

                    b.HasIndex("PlayerId", "Season");

                    b.HasIndex("PlayerId", "Season", "GameType", "LeagueAbbrev", "TeamName")
                        .IsUnique()
                        .HasFilter("[TeamName] IS NOT NULL");

                    b.ToTable("PlayerCareerSeasonStats", (string)null);
                });

            modelBuilder.Entity("FantasyWarrior.Data.Entities.PlayerContract", b =>
                {
                    b.Property<int>("PlayerContractId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerContractId"));

                    b.Property<long?>("Aav")
                        .HasColumnType("bigint");

                    b.Property<long>("CapHit")
                        .HasColumnType("bigint");

                    b.Property<string>("ClauseType")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("ImportedUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("char(8)")
                        .IsFixedLength();

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)");

                    b.Property<long?>("TotalValue")
                        .HasColumnType("bigint");

                    b.Property<int?>("YearsRemaining")
                        .HasColumnType("int");

                    b.HasKey("PlayerContractId");

                    b.HasIndex("PlayerId", "Season")
                        .IsUnique();

                    b.ToTable("PlayerContracts", (string)null);
                });

            modelBuilder.Entity("FantasyWarrior.Data.Entities.PlayerGameStat", b =>
                {
                    b.Property<long>("GameId")
                        .HasColumnType("bigint");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<int?>("Assists")
                        .HasColumnType("int");

                    b.Property<int?>("BlockedShots")
                        .HasColumnType("int");

                    b.Property<string>("Decision")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.Property<DateOnly>("GameDate")
                        .HasColumnType("date");

                    b.Property<byte>("GameType")
                        .HasColumnType("tinyint");

                    b.Property<int?>("Goals")
                        .HasColumnType("int");

                    b.Property<int?>("GoalsAgainst")
                        .HasColumnType("int");

                    b.Property<int?>("Hits")
                        .HasColumnType("int");

                    b.Property<bool>("IsGoalie")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHome")
                        .HasColumnType("bit");

                    b.Property<string>("OpponentAbbrev")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .IsFixedLength();

                    b.Property<bool?>("OtLoss")
                        .HasColumnType("bit");

                    b.Property<int>("Pim")
                        .HasColumnType("int");

                    b.Property<int?>("PlusMinus")
                        .HasColumnType("int");

                    b.Property<int?>("Points")
                        .HasColumnType("int");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.Property<int?>("PowerPlayGoals")
                        .HasColumnType("int");

                    b.Property<int?>("Saves")
                        .HasColumnType("int");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("char(8)")
                        .IsFixedLength();

                    b.Property<int?>("Shots")
                        .HasColumnType("int");

                    b.Property<int?>("ShotsAgainst")
                        .HasColumnType("int");

                    b.Property<bool?>("Shutout")
                        .HasColumnType("bit");

                    b.Property<bool?>("Starter")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SyncedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TeamAbbrev")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .IsFixedLength();

                    b.Property<string>("Toi")
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)");

                    b.HasKey("GameId", "PlayerId");

                    b.HasIndex("GameDate");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("GameDate"), new[] { "PlayerId", "Season", "GameType", "IsGoalie", "Goals", "Assists", "PlusMinus", "Pim", "Shots", "Hits", "BlockedShots", "Decision", "OtLoss", "Shutout", "GoalsAgainst", "Saves", "ShotsAgainst" });

                    b.HasIndex("PlayerId", "GameDate");

                    b.ToTable("PlayerGameStats", (string)null);
                });

            modelBuilder.Entity("FantasyWarrior.Data.Entities.PlayerInjury", b =>
                {
                    b.Property<int>("PlayerInjuryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerInjuryId"));

                    b.Property<DateOnly?>("ExpectedReturn")
                        .HasColumnType("date");

                    b.Property<string>("InjuryType")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ReportedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ResolvedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("PlayerInjuryId");

                    b.HasIndex("PlayerId")
                        .HasFilter("[ResolvedUtc] IS NULL");

                    b.ToTable("PlayerInjuries", (string)null);
                });

            modelBuilder.Entity("FantasyWarrior.Data.Entities.RosterAssignment", b =>
                {
                    b.Property<int>("RosterAssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RosterAssignmentId"));

                    b.Property<int>("Assists")
                        .HasColumnType("int");

                    b.Property<int>("BlockedShots")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<double>("FantasyPoints")
                        .HasColumnType("float");

                    b.Property<int>("GamesPlayed")
                        .HasColumnType("int");

                    b.Property<int>("Goals")
                        .HasColumnType("int");

                    b.Property<int>("GoalsAgainst")
                        .HasColumnType("int");

                    b.Property<int>("Hits")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFinalized")
                        .HasColumnType("bit");

                    b.Property<int>("OtLosses")
                        .HasColumnType("int");

                    b.Property<int>("PeriodId")
                        .HasColumnType("int");

                    b.Property<int>("Pim")
                        .HasColumnType("int");

                    b.Property<int>("PlusMinus")
                        .HasColumnType("int");

                    b.Property<int>("RosterSpotId")
                        .HasColumnType("int");

                    b.Property<int>("Saves")
                        .HasColumnType("int");

                    b.Property<DateTime>("ScoredUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Shots")
                        .HasColumnType("int");

                    b.Property<int>("ShotsAgainst")
                        .HasColumnType("int");

                    b.Property<int>("Shutouts")
                        .HasColumnType("int");

                    b.Property<int>("TeamLosses")
                        .HasColumnType("int");

                    b.Property<int>("TeamOtLosses")
                        .HasColumnType("int");

                    b.Property<int>("TeamWins")
                        .HasColumnType("int");

                    b.Property<int>("Wins")
                        .HasColumnType("int");

                    b.HasKey("RosterAssignmentId");

                    b.HasIndex("PeriodId", "IsActive");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("PeriodId", "IsActive"), new[] { "RosterSpotId", "FantasyPoints", "GamesPlayed" });

                    b.HasIndex("RosterSpotId", "PeriodId")
                        .IsUnique();

                    b.ToTable("RosterAssignments", (string)null);
                });

            modelBuilder.Entity("FantasyWarrior.Data.Entities.RosterSpot", b =>
                {
                    b.Property<int>("RosterSpotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RosterSpotId"));

                    b.Property<DateTime?>("ClosedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<byte?>("EndReason")
                        .HasColumnType("tinyint");

                    b.Property<int?>("EndTradeId")
                        .HasColumnType("int");

                    b.Property<string>("FranchiseAbbrev")
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .IsFixedLength();

                    b.Property<int>("LeagueId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OpenedUtc")
                        .HasColumnType("datetime2");

                    b.Property<long?>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<string>("PositionGroup")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int?>("StartDraftPickId")
                        .HasColumnType("int");

                    b.Property<byte>("StartReason")
                        .HasColumnType("tinyint");

                    b.Property<int?>("StartTradeId")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("RosterSpotId");

                    b.HasIndex("EndTradeId");

                    b.HasIndex("FranchiseAbbrev");

                    b.HasIndex("PlayerId");

                    b.HasIndex("StartDraftPickId");

                    b.HasIndex("StartTradeId");

                    b.HasIndex("LeagueId", "FranchiseAbbrev")
                        .IsUnique()
                        .HasDatabaseName("UX_RosterSpots_OneOpenFranchisePerLeague")
                        .HasFilter("[EndDate] IS NULL AND [FranchiseAbbrev] IS NOT NULL");

                    b.HasIndex("LeagueId", "PlayerId")
                        .IsUnique()
                        .HasDatabaseName("UX_RosterSpots_OneOpenSpotPerPlayerPerLeague")
                        .HasFilter("[EndDate] IS NULL AND [PlayerId] IS NOT NULL");

                    b.HasIndex("LeagueId", "StartDate", "EndDate");

                    b.HasIndex(new[] { "TeamId" }, "IX_RosterSpots_TeamId")
                        .HasFilter("[EndDate] IS NULL");

                    b.HasIndex(new[] { "TeamId" }, "UX_RosterSpots_OneOpenFranchisePerTeam")
                        .IsUnique()
                        .HasFilter("[EndDate] IS NULL AND [PositionGroup] = 'T'");

                    b.ToTable("RosterSpots", null, t =>
                        {
                            t.HasCheckConstraint("CK_RosterSpots_PlayerOrFranchise", "([PositionGroup] = 'T' AND [FranchiseAbbrev] IS NOT NULL AND [PlayerId] IS NULL) OR ([PositionGroup] <> 'T' AND [PlayerId] IS NOT NULL AND [FranchiseAbbrev] IS NULL)");
                        });
                });

            modelBuilder.Entity("FantasyWarrior.Data.Entities.SimulationState", b =>
                {
                    b.Property<byte>("SimulationStateId")
                        .HasColumnType("tinyint");

                    b.Property<DateOnly>("AsOfDate")
                        .HasColumnType("date");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("char(8)")
                        .IsFixedLength();

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("SimulationStateId");

                    b.ToTable("SimulationState", null, t =>
                        {
                            t.HasCheckConstraint("CK_SimulationState_SingleRow", "[SimulationStateId] = 1");
                        });
                });

            modelBuilder.Entity("FantasyWarrior.Data.Entities.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeamId"));

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("FranchiseAbbrev")
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .IsFixedLength();

                    b.Property<int>("LeagueId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("OwnerUserId")
                        .HasColumnType("int");

                    b.HasKey("TeamId");

                    b.HasIndex("FranchiseAbbrev");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("LeagueId", "OwnerUserId")
                        .IsUnique();

                    b.ToTable("Teams", (string)null);
                });

            modelBuilder.Entity("FantasyWarrior.Data.Entities.TeamPeriodLineup", b =>
                {
                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<int>("PeriodId")
                        .HasColumnType("int");

                    b.Property<string>("SetBy")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("SubmittedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("TeamId", "PeriodId");

                    b.HasIndex("PeriodId");

                    b.ToTable("TeamPeriodLineups", (string)null);
                });

            modelBuilder.Entity("FantasyWarrior.Data.Entities.Trade", b =>
                {
                    b.Property<int>("TradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TradeId"));

                    b.Property<int>("CounterpartyTeamId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<int>("LeagueId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ProcessedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProposerTeamId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RespondedUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("TradeId");

                    b.HasIndex("CounterpartyTeamId");

                    b.HasIndex("ProposerTeamId");

                    b.HasIndex("Status")
                        .HasFilter("[Status] = 3");

                    b.HasIndex("LeagueId", "CreatedUtc")
                        .IsDescending(false, true);

                    b.ToTable("Trades", (string)null);
                });

            modelBuilder.Entity("FantasyWarrior.Data.Entities.TradeAsset", b =>
                {
                    b.Property<int>("TradeAssetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TradeAssetId"));

                    b.Property<byte>("AssetType")
                        .HasColumnType("tinyint");

                    b.Property<int?>("DraftPickId")
                        .HasColumnType("int");

                    b.Property<string>("FranchiseAbbrev")
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .IsFixedLength();

                    b.Property<int>("FromTeamId")
                        .HasColumnType("int");

                    b.Property<long?>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<int>("ToTeamId")
                        .HasColumnType("int");

                    b.Property<int>("TradeId")
                        .HasColumnType("int");

                    b.HasKey("TradeAssetId");

                    b.HasIndex("DraftPickId");

                    b.HasIndex("FranchiseAbbrev");

                    b.HasIndex("FromTeamId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("ToTeamId");

                    b.HasIndex("TradeId");

                    b.ToTable("TradeAssets", null, t =>
                        {
                            t.HasCheckConstraint("CK_TradeAssets_ExactlyOneAsset", "([AssetType] = 0 AND [PlayerId] IS NOT NULL AND [DraftPickId] IS NULL AND [FranchiseAbbrev] IS NULL) OR ([AssetType] = 1 AND [DraftPickId] IS NOT NULL AND [PlayerId] IS NULL AND [FranchiseAbbrev] IS NULL) OR ([AssetType] = 2 AND [FranchiseAbbrev] IS NOT NULL AND [PlayerId] IS NULL AND [DraftPickId] IS NULL)");
                        });
                });

            modelBuilder.Entity("FantasyWarrior.Data.Entities.TradeVote", b =>
                {
                    b.Property<int>("TradeId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("FavoredTeamId")
                        .HasColumnType("int");

                    b.Property<DateTime>("VotedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("TradeId", "UserId");

                    b.HasIndex("FavoredTeamId");

                    b.HasIndex("UserId");

                    b.ToTable("TradeVotes", (string)null);
                });

            modelBuilder.Entity("FantasyWarrior.Data.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ExternalAuthId")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime?>("LastLoginUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastSeenUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.HasKey("UserId");

                    b.HasIndex("ExternalAuthId")
                        .IsUnique()
                        .HasFilter("[ExternalAuthId] IS NOT NULL");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("FantasyWarrior.Data.Entities.Views.CockcoinBalanceView", b =>
                {
                    b.Property<int>("Balance")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("vCockcoinBalance", (string)null);
                });

            modelBuilder.Entity("FantasyWarrior.Data.Entities.Views.PlayerSeasonStatsView", b =>
                {
                    b.Property<int>("Assists")
                        .HasColumnType("int");

                    b.Property<int>("BlockedShots")
                        .HasColumnType("int");

                    b.Property<int>("GamesPlayed")
                        .HasColumnType("int");

                    b.Property<int>("Goals")
                        .HasColumnType("int");

                    b.Property<int>("GoalsAgainst")
                        .HasColumnType("int");

                    b.Property<int>("Hits")
                        .HasColumnType("int");

                    b.Property<int>("OtLosses")
                        .HasColumnType("int");

                    b.Property<int>("Pim")
                        .HasColumnType("int");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<int>("PlusMinus")
                        .HasColumnType("int");

                    b.Property<int>("Saves")
                        .HasColumnType("int");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Shots")
                        .HasColumnType("int");

                    b.Property<int>("ShotsAgainst")
                        .HasColumnType("int");

                    b.Property<int>("Shutouts")
                        .HasColumnType("int");

                    b.Property<int>("Wins")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("vPlayerSeasonStats", (string)null);
                });

            modelBuilder.Entity("FantasyWarrior.Data.Entities.Views.PoolerTradeRecordView", b =>
                {
                    b.Property<int>("LeagueId")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<double?>("TraderRating")
                        .HasColumnType("float");

                    b.Property<int>("TradesFair")
                        .HasColumnType("int");

                    b.Property<int>("TradesLost")
                        .HasColumnType("int");

                    b.Property<int>("TradesTotal")
                        .HasColumnType("int");

                    b.Property<int>("TradesWon")
                        .HasColumnType("int");

                    b.Property<int>("VotesAgainst")
                        .HasColumnType("int");

                    b.Property<int>("VotesFair")
                        .HasColumnType("int");

                    b.Property<int>("VotesFor")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("vPoolerTradeRecord", (string)null);
                });

            modelBuilder.Entity("FantasyWarrior.Data.Entities.Views.RosterSpotTotalsView", b =>
                {
                    b.Property<int>("ActiveAssists")
                        .HasColumnType("int");

                    b.Property<int>("ActiveGamesPlayed")
                        .HasColumnType("int");

                    b.Property<int>("ActiveGoals")
                        .HasColumnType("int");

                    b.Property<double>("ActivePoints")
                        .HasColumnType("float");

                    b.Property<int>("ActiveTeamLosses")
                        .HasColumnType("int");

                    b.Property<int>("ActiveTeamOtLosses")
                        .HasColumnType("int");

                    b.Property<int>("ActiveTeamWins")
                        .HasColumnType("int");

                    b.Property<double>("BenchPoints")
                        .HasColumnType("float");

                    b.Property<double>("FinalizedActivePoints")
                        .HasColumnType("float");

                    b.Property<string>("FranchiseAbbrev")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LeagueId")
                        .HasColumnType("int");

                    b.Property<long?>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<int>("RosterSpotId")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("vRosterSpotTotals", (string)null);
                });

            modelBuilder.Entity("FantasyWarrior.Data.Entities.Views.StandingsView", b =>
                {
                    b.Property<double>("BenchScore")
                        .HasColumnType("float");

                    b.Property<long>("CapTotal")
                        .HasColumnType("bigint");

                    b.Property<long>("EngagedCapTotal")
                        .HasColumnType("bigint");

                    b.Property<int>("EngagedPlayerCount")
                        .HasColumnType("int");

                    b.Property<int>("EngagedUnknownContracts")
                        .HasColumnType("int");

                    b.Property<double>("FinalizedScore")
                        .HasColumnType("float");

                    b.Property<int>("LeagueId")
                        .HasColumnType("int");

                    b.Property<double>("LivePoints")
                        .HasColumnType("float");

                    b.Property<int>("PlayerCount")
                        .HasColumnType("int");

                    b.Property<int>("RosterGamesPlayed")
                        .HasColumnType("int");

                    b.Property<double>("Score")
                        .HasColumnType("float");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<int>("UnknownContracts")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("vStandings", (string)null);
                });

            modelBuilder.Entity("FantasyWarrior.Data.Entities.Views.TeamPeriodScoreView", b =>
                {
                    b.Property<double>("ActivePoints")
                        .HasColumnType("float");

                    b.Property<double>("BenchPoints")
                        .HasColumnType("float");

                    b.Property<bool>("IsFinalized")
                        .HasColumnType("bit");

                    b.Property<int>("PeriodId")
                        .HasColumnType("int");

                    b.Property<int>("PeriodNumber")
                        .HasColumnType("int");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("vTeamPeriodScores", (string)null);
                });

            modelBuilder.Entity("FantasyWarrior.Data.Entities.CockcoinAward", b =>
                {
                    b.HasOne("FantasyWarrior.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FantasyWarrior.Data.Entities.DraftPick", b =>
                {
                    b.HasOne("FantasyWarrior.Data.Entities.Team", "CurrentTeam")
                        .WithMany()
                        .HasForeignKey("CurrentTeamId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FantasyWarrior.Data.Entities.League", "League")
                        .WithMany("DraftPicks")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FantasyWarrior.Data.Entities.Team", "OriginalTeam")
                        .WithMany()
                        .HasForeignKey("OriginalTeamId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FantasyWarrior.Data.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CurrentTeam");

                    b.Navigation("League");

                    b.Navigation("OriginalTeam");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("FantasyWarrior.Data.Entities.Game", b =>
                {
                    b.HasOne("FantasyWarrior.Data.Entities.NhlTeam", null)
                        .WithMany()
                        .HasForeignKey("AwayTeamAbbrev")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FantasyWarrior.Data.Entities.NhlTeam", null)
                        .WithMany()
                        .HasForeignKey("HomeTeamAbbrev")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("FantasyWarrior.Data.Entities.League", b =>
                {
                    b.HasOne("FantasyWarrior.Data.Entities.User", "Commissioner")
                        .WithMany()
                        .HasForeignKey("CommissionerUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Commissioner");
                });

            modelBuilder.Entity("FantasyWarrior.Data.Entities.LeagueMember", b =>
                {
                    b.HasOne("FantasyWarrior.Data.Entities.League", "League")
                        .WithMany("Members")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FantasyWarrior.Data.Entities.User", "User")
                        .WithMany("Memberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("League");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FantasyWarrior.Data.Entities.LeagueScoringRule", b =>
                {
                    b.HasOne("FantasyWarrior.Data.Entities.League", "League")
                        .WithMany("ScoringRules")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");
                });

            modelBuilder.Entity("FantasyWarrior.Data.Entities.Message", b =>
                {
                    b.HasOne("FantasyWarrior.Data.Entities.League", "League")
                        .WithMany()
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FantasyWarrior.Data.Entities.User", "Recipient")
                        .WithMany()
                        .HasForeignKey("RecipientUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FantasyWarrior.Data.Entities.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("League");

                    b.Navigation("Recipient");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("FantasyWarrior.Data.Entities.NewsItem", b =>
                {
                    b.HasOne("FantasyWarrior.Data.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Player");
                });

            modelBuilder.Entity("FantasyWarrior.Data.Entities.Player", b =>
                {
                    b.HasOne("FantasyWarrior.Data.Entities.NhlTeam", "Team")
                        .WithMany()
                        .HasForeignKey("TeamAbbrev")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Team");
                });

            modelBuilder.Entity("FantasyWarrior.Data.Entities.PlayerCareerSeasonStat", b =>
                {
                    b.HasOne("FantasyWarrior.Data.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("FantasyWarrior.Data.Entities.PlayerContract", b =>
                {
                    b.HasOne("FantasyWarrior.Data.Entities.Player", "Player")
                        .WithMany("Contracts")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("FantasyWarrior.Data.Entities.PlayerGameStat", b =>
                {
                    b.HasOne("FantasyWarrior.Data.Entities.Game", "Game")
                        .WithMany("PlayerLines")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FantasyWarrior.Data.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("FantasyWarrior.Data.Entities.PlayerInjury", b =>
                {
                    b.HasOne("FantasyWarrior.Data.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("FantasyWarrior.Data.Entities.RosterAssignment", b =>
                {
                    b.HasOne("FantasyWarrior.Data.Entities.Period", "Period")
                        .WithMany("Assignments")
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FantasyWarrior.Data.Entities.RosterSpot", "RosterSpot")
                        .WithMany("Assignments")
                        .HasForeignKey("RosterSpotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Period");

                    b.Navigation("RosterSpot");
                });

            modelBuilder.Entity("FantasyWarrior.Data.Entities.RosterSpot", b =>
                {
                    b.HasOne("FantasyWarrior.Data.Entities.Trade", "EndTrade")
                        .WithMany()
                        .HasForeignKey("EndTradeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("FantasyWarrior.Data.Entities.NhlTeam", "Franchise")
                        .WithMany()
                        .HasForeignKey("FranchiseAbbrev")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("FantasyWarrior.Data.Entities.League", "League")
                        .WithMany("RosterSpots")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FantasyWarrior.Data.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("FantasyWarrior.Data.Entities.DraftPick", "StartDraftPick")
                        .WithMany()
                        .HasForeignKey("StartDraftPickId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("FantasyWarrior.Data.Entities.Trade", "StartTrade")
                        .WithMany()
                        .HasForeignKey("StartTradeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("FantasyWarrior.Data.Entities.Team", "Team")
                        .WithMany("RosterSpots")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EndTrade");

                    b.Navigation("Franchise");

                    b.Navigation("League");

                    b.Navigation("Player");

                    b.Navigation("StartDraftPick");

                    b.Navigation("StartTrade");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("FantasyWarrior.Data.Entities.Team", b =>
                {
                    b.HasOne("FantasyWarrior.Data.Entities.NhlTeam", "Franchise")
                        .WithMany()
                        .HasForeignKey("FranchiseAbbrev")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("FantasyWarrior.Data.Entities.League", "League")
                        .WithMany("Teams")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FantasyWarrior.Data.Entities.User", "Owner")
                        .WithMany("Teams")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Franchise");

                    b.Navigation("League");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("FantasyWarrior.Data.Entities.TeamPeriodLineup", b =>
                {
                    b.HasOne("FantasyWarrior.Data.Entities.Period", "Period")
                        .WithMany()
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FantasyWarrior.Data.Entities.Team", "Team")
                        .WithMany("Lineups")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Period");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("FantasyWarrior.Data.Entities.Trade", b =>
                {
                    b.HasOne("FantasyWarrior.Data.Entities.Team", "CounterpartyTeam")
                        .WithMany()
                        .HasForeignKey("CounterpartyTeamId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FantasyWarrior.Data.Entities.League", "League")
                        .WithMany("Trades")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FantasyWarrior.Data.Entities.Team", "ProposerTeam")
                        .WithMany()
                        .HasForeignKey("ProposerTeamId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CounterpartyTeam");

                    b.Navigation("League");

                    b.Navigation("ProposerTeam");
                });

            modelBuilder.Entity("FantasyWarrior.Data.Entities.TradeAsset", b =>
                {
                    b.HasOne("FantasyWarrior.Data.Entities.DraftPick", "DraftPick")
                        .WithMany()
                        .HasForeignKey("DraftPickId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("FantasyWarrior.Data.Entities.NhlTeam", "Franchise")
                        .WithMany()
                        .HasForeignKey("FranchiseAbbrev")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("FantasyWarrior.Data.Entities.Team", "FromTeam")
                        .WithMany()
                        .HasForeignKey("FromTeamId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FantasyWarrior.Data.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("FantasyWarrior.Data.Entities.Team", "ToTeam")
                        .WithMany()
                        .HasForeignKey("ToTeamId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FantasyWarrior.Data.Entities.Trade", "Trade")
                        .WithMany("Assets")
                        .HasForeignKey("TradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DraftPick");

                    b.Navigation("Franchise");

                    b.Navigation("FromTeam");

                    b.Navigation("Player");

                    b.Navigation("ToTeam");

                    b.Navigation("Trade");
                });

            modelBuilder.Entity("FantasyWarrior.Data.Entities.TradeVote", b =>
                {
                    b.HasOne("FantasyWarrior.Data.Entities.Team", "FavoredTeam")
                        .WithMany()
                        .HasForeignKey("FavoredTeamId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("FantasyWarrior.Data.Entities.Trade", "Trade")
                        .WithMany("Votes")
                        .HasForeignKey("TradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FantasyWarrior.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("FavoredTeam");

                    b.Navigation("Trade");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FantasyWarrior.Data.Entities.Game", b =>
                {
                    b.Navigation("PlayerLines");
                });

            modelBuilder.Entity("FantasyWarrior.Data.Entities.League", b =>
                {
                    b.Navigation("DraftPicks");

                    b.Navigation("Members");

                    b.Navigation("RosterSpots");

                    b.Navigation("ScoringRules");

                    b.Navigation("Teams");

                    b.Navigation("Trades");
                });

            modelBuilder.Entity("FantasyWarrior.Data.Entities.Period", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("FantasyWarrior.Data.Entities.Player", b =>
                {
                    b.Navigation("Contracts");
                });

            modelBuilder.Entity("FantasyWarrior.Data.Entities.RosterSpot", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("FantasyWarrior.Data.Entities.Team", b =>
                {
                    b.Navigation("Lineups");

                    b.Navigation("RosterSpots");
                });

            modelBuilder.Entity("FantasyWarrior.Data.Entities.Trade", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("FantasyWarrior.Data.Entities.User", b =>
                {
                    b.Navigation("Memberships");

                    b.Navigation("Teams");
                });
#pragma warning restore 612, 618
        }
    }
}
